package pl.altkom.jpr.tools.hotelsrank.hotelrankbrowser.engine.tools;

import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author Leszek Bednorz
 */
public class Countrys {

    private static transient Countrys instance;

    public static Countrys getInstance() {
        if (instance == null) {
            synchronized (Countrys.class) {
                if (instance == null) {
                    instance = new Countrys();
                }
            }
        }
        return instance;
    }
    private Map<String, String> coutryCodes = new HashMap<String, String>();

    private Countrys() {

        coutryCodes.put("Afghanistan".toUpperCase(), "AF");
        coutryCodes.put("Albania".toUpperCase(), "AL");
        coutryCodes.put("Algeria".toUpperCase(), "DZ");
        coutryCodes.put("Andorra".toUpperCase(), "AD");
        coutryCodes.put("Angola".toUpperCase(), "AO");
        coutryCodes.put("Anguilla".toUpperCase(), "AI");
        coutryCodes.put("Antigua And Barbuda".toUpperCase(), "AG");
        coutryCodes.put("Saudi Arabia".toUpperCase(), "SA");
        coutryCodes.put("Argentina".toUpperCase(), "AR");
        coutryCodes.put("Armenia".toUpperCase(), "AM");
        coutryCodes.put("Aruba".toUpperCase(), "AW");
        coutryCodes.put("Australia".toUpperCase(), "AU");
        coutryCodes.put("Austria".toUpperCase(), "AT");
        coutryCodes.put("Azerbaijan".toUpperCase(), "AZ");
        coutryCodes.put("Bahamas".toUpperCase(), "BS");
        coutryCodes.put("Bahrain".toUpperCase(), "BH");
        coutryCodes.put("Bangladesh".toUpperCase(), "BD");
        coutryCodes.put("Barbados".toUpperCase(), "BB");
        coutryCodes.put("Belgium".toUpperCase(), "BE");
        coutryCodes.put("Belize".toUpperCase(), "BZ");
        coutryCodes.put("Benin".toUpperCase(), "BJ");
        coutryCodes.put("Bermudas".toUpperCase(), "BM");
        coutryCodes.put("Bhutan".toUpperCase(), "BT");
        coutryCodes.put("Belarus".toUpperCase(), "BY");
        coutryCodes.put("Burma".toUpperCase(), "MM");
        coutryCodes.put("Bolivia".toUpperCase(), "BO");
        coutryCodes.put("Bonaire, Sint Eustatius And Saba".toUpperCase(), "BQ");
        coutryCodes.put("Bosnia And Herzegovina".toUpperCase(), "BA");
        coutryCodes.put("Botswana".toUpperCase(), "BW");
        coutryCodes.put("Brazil".toUpperCase(), "BR");
        coutryCodes.put("Brunei".toUpperCase(), "BN");
        coutryCodes.put("Bulgaria".toUpperCase(), "BG");
        coutryCodes.put("Burkina Faso".toUpperCase(), "BF");
        coutryCodes.put("Burundi".toUpperCase(), "BI");
        coutryCodes.put("Ceuta".toUpperCase(), "XC");
        coutryCodes.put("Chile".toUpperCase(), "CL");
        coutryCodes.put("China".toUpperCase(), "CN");
        coutryCodes.put("Croatia".toUpperCase(), "HR");
        coutryCodes.put("Curacao".toUpperCase(), "CW");
        coutryCodes.put("Cyprus".toUpperCase(), "CY");
        coutryCodes.put("Chad".toUpperCase(), "TD");
        coutryCodes.put("Montenegro".toUpperCase(), "ME");
        coutryCodes.put("Czech Republic".toUpperCase(), "CZ");
        coutryCodes.put("Denmark".toUpperCase(), "DK");
        coutryCodes.put("Dominica".toUpperCase(), "DM");
        coutryCodes.put("Dominican Republic".toUpperCase(), "DO");
        coutryCodes.put("Djibouti".toUpperCase(), "DJ");
        coutryCodes.put("Egypt".toUpperCase(), "EG");
        coutryCodes.put("Ecuador".toUpperCase(), "EC");
        coutryCodes.put("Eritrea".toUpperCase(), "ER");
        coutryCodes.put("Estonia".toUpperCase(), "EE");
        coutryCodes.put("Ethiopia".toUpperCase(), "ET");
        coutryCodes.put("Falklands".toUpperCase(), "FK");
        coutryCodes.put("Republic Of Fiji".toUpperCase(), "FJ");
        coutryCodes.put("Philippines".toUpperCase(), "PH");
        coutryCodes.put("Finland".toUpperCase(), "FI");
        coutryCodes.put("France".toUpperCase(), "FR");
        coutryCodes.put("Gabon".toUpperCase(), "GA");
        coutryCodes.put("Gambia".toUpperCase(), "GM");
        coutryCodes.put("Ghana".toUpperCase(), "GH");
        coutryCodes.put("Gibraltar".toUpperCase(), "GI");
        coutryCodes.put("Greece".toUpperCase(), "GR");
        coutryCodes.put("Grenada".toUpperCase(), "GD");
        coutryCodes.put("Greenland".toUpperCase(), "GL");
        coutryCodes.put("Georgia".toUpperCase(), "GE");
        coutryCodes.put("Guam".toUpperCase(), "GU");
        coutryCodes.put("Guyana".toUpperCase(), "GY");
        coutryCodes.put("Guatemala".toUpperCase(), "GT");
        coutryCodes.put("Guinea".toUpperCase(), "GN");
        coutryCodes.put("Equatorial Guinea".toUpperCase(), "GQ");
        coutryCodes.put("Guinea -Bissau".toUpperCase(), "GW");
        coutryCodes.put("Haiti".toUpperCase(), "HT");
        coutryCodes.put("Spain".toUpperCase(), "ES");
        coutryCodes.put("Netherlands".toUpperCase(), "NL");
        coutryCodes.put("Honduras".toUpperCase(), "HN");
        coutryCodes.put("Hong Kong".toUpperCase(), "HK");
        coutryCodes.put("India".toUpperCase(), "IN");
        coutryCodes.put("Indonesia".toUpperCase(), "ID");
        coutryCodes.put("Iraq".toUpperCase(), "IQ");
        coutryCodes.put("Iran".toUpperCase(), "IR");
        coutryCodes.put("Ireland".toUpperCase(), "IE");
        coutryCodes.put("Iceland".toUpperCase(), "IS");
        coutryCodes.put("Israel".toUpperCase(), "IL");
        coutryCodes.put("Jamaica".toUpperCase(), "JM");
        coutryCodes.put("Japan".toUpperCase(), "JP");
        coutryCodes.put("Yemen".toUpperCase(), "YE");
        coutryCodes.put("Jordan".toUpperCase(), "JO");
        coutryCodes.put("Cayman Islands".toUpperCase(), "KY");
        coutryCodes.put("Cambodia".toUpperCase(), "KH");
        coutryCodes.put("Cameroon".toUpperCase(), "CM");
        coutryCodes.put("Canada".toUpperCase(), "CA");
        coutryCodes.put("Qatar".toUpperCase(), "QA");
        coutryCodes.put("Kazakhstan".toUpperCase(), "KZ");
        coutryCodes.put("Kenya".toUpperCase(), "KE");
        coutryCodes.put("Kyrgyzstan".toUpperCase(), "KG");
        coutryCodes.put("Kiribati".toUpperCase(), "KI");
        coutryCodes.put("Colombia".toUpperCase(), "CO");
        coutryCodes.put("Chamber".toUpperCase(), "KM");
        coutryCodes.put("Congo, Democratic Republic".toUpperCase(), "CD");
        coutryCodes.put("Kongo".toUpperCase(), "CG");
        coutryCodes.put("South Korea".toUpperCase(), "KR");
        coutryCodes.put("North Korea".toUpperCase(), "KP");
        coutryCodes.put("Kosovo".toUpperCase(), "XK");
        coutryCodes.put("Costa Rica".toUpperCase(), "CR");
        coutryCodes.put("Cuba".toUpperCase(), "CU");
        coutryCodes.put("Kuwait".toUpperCase(), "KW");
        coutryCodes.put("Laos".toUpperCase(), "LA");
        coutryCodes.put("Lesotho".toUpperCase(), "LS");
        coutryCodes.put("Lebanon".toUpperCase(), "LB");
        coutryCodes.put("Liberia".toUpperCase(), "LR");
        coutryCodes.put("Libya".toUpperCase(), "LY");
        coutryCodes.put("Liechtenstein".toUpperCase(), "LI");
        coutryCodes.put("Lithuania".toUpperCase(), "LT");
        coutryCodes.put("Luxembourg".toUpperCase(), "LU");
        coutryCodes.put("Latvia".toUpperCase(), "LV");
        coutryCodes.put("Macedonia".toUpperCase(), "MK");
        coutryCodes.put("Madagascar".toUpperCase(), "MG");
        coutryCodes.put("Mayotte".toUpperCase(), "YT");
        coutryCodes.put("Macau".toUpperCase(), "MO");
        coutryCodes.put("Malawi".toUpperCase(), "MW");
        coutryCodes.put("Maldives".toUpperCase(), "MV");
        coutryCodes.put("Malaysia".toUpperCase(), "MY");
        coutryCodes.put("Mali".toUpperCase(), "ML");
        coutryCodes.put("Malta".toUpperCase(), "MT");
        coutryCodes.put("Northern Mariana Islands".toUpperCase(), "MP");
        coutryCodes.put("Morocco".toUpperCase(), "MA");
        coutryCodes.put("Marshall Islands,".toUpperCase(), "MH");
        coutryCodes.put("Mauritania".toUpperCase(), "MR");
        coutryCodes.put("Mauritius".toUpperCase(), "MU");
        coutryCodes.put("Mexico".toUpperCase(), "MX");
        coutryCodes.put("Melilla".toUpperCase(), "XL");
        coutryCodes.put("Micronesia , Federated".toUpperCase(), "FM");
        coutryCodes.put("Moldova".toUpperCase(), "MD");
        coutryCodes.put("Monaco".toUpperCase(), "MC");
        coutryCodes.put("Mongolia".toUpperCase(), "MN");
        coutryCodes.put("Montserrat".toUpperCase(), "MS");
        coutryCodes.put("Mozambique".toUpperCase(), "MZ");
        coutryCodes.put("Namibia".toUpperCase(), "NA");
        coutryCodes.put("Nauru".toUpperCase(), "NR");
        coutryCodes.put("Nepal".toUpperCase(), "NP");
        coutryCodes.put("Germany".toUpperCase(), "DE");
        coutryCodes.put("Niger".toUpperCase(), "NE");
        coutryCodes.put("Nigeria".toUpperCase(), "NG");
        coutryCodes.put("Nicaragua".toUpperCase(), "NI");
        coutryCodes.put("Niue".toUpperCase(), "NU");
        coutryCodes.put("Norfolk".toUpperCase(), "NF");
        coutryCodes.put("Norway".toUpperCase(), "NO");
        coutryCodes.put("New Caledonia".toUpperCase(), "NC");
        coutryCodes.put("New Zealand".toUpperCase(), "NZ");
        coutryCodes.put("Oman".toUpperCase(), "OM");
        coutryCodes.put("Pakistan".toUpperCase(), "PK");
        coutryCodes.put("Palau".toUpperCase(), "PW");
        coutryCodes.put("Panama".toUpperCase(), "PA");
        coutryCodes.put("Papua New Guinea".toUpperCase(), "PG");
        coutryCodes.put("Paraguay".toUpperCase(), "PY");
        coutryCodes.put("Peru".toUpperCase(), "PE");
        coutryCodes.put("Pitcairn".toUpperCase(), "PN");
        coutryCodes.put("French Polynesia".toUpperCase(), "PF");
        coutryCodes.put("Poland".toUpperCase(), "PL");
        coutryCodes.put("South Georgia And South Sandwich Islands".toUpperCase(), "GS");
        coutryCodes.put("Puerto Rico".toUpperCase(), "PR");
        coutryCodes.put("Portugal".toUpperCase(), "PT");
        coutryCodes.put("South Africa (South Africa)".toUpperCase(), "ZA");
        coutryCodes.put("Central African Republic".toUpperCase(), "CF");
        coutryCodes.put("Cape Verde".toUpperCase(), "CV");
        coutryCodes.put("Russia".toUpperCase(), "RU");
        coutryCodes.put("Romania".toUpperCase(), "RO");
        coutryCodes.put("Ruanda".toUpperCase(), "RW");
        coutryCodes.put("Western Sahara".toUpperCase(), "EH");
        coutryCodes.put("Saint Barthelemy".toUpperCase(), "BL");
        coutryCodes.put("Saint Christopher And Nevis".toUpperCase(), "KN");
        coutryCodes.put("Saint Lucia".toUpperCase(), "LC");
        coutryCodes.put("Saint Vincent And The Grenadines".toUpperCase(), "VC");
        coutryCodes.put("Solomon Islands".toUpperCase(), "SB");
        coutryCodes.put("El Salvador".toUpperCase(), "SV");
        coutryCodes.put("Samoa".toUpperCase(), "WS");
        coutryCodes.put("American Samoa".toUpperCase(), "AS");
        coutryCodes.put("San Marino".toUpperCase(), "SM");
        coutryCodes.put("Senegal".toUpperCase(), "SN");
        coutryCodes.put("Serbia".toUpperCase(), "XS");
        coutryCodes.put("Seychelles".toUpperCase(), "SC");
        coutryCodes.put("Sierra Leone".toUpperCase(), "SL");
        coutryCodes.put("Singapore".toUpperCase(), "SG");
        coutryCodes.put("Slovakia".toUpperCase(), "SK");
        coutryCodes.put("Slovenia".toUpperCase(), "SI");
        coutryCodes.put("Somalia".toUpperCase(), "SO");
        coutryCodes.put("Sri Lanka".toUpperCase(), "LK");
        coutryCodes.put("St . Pierre And Miquelon".toUpperCase(), "PM");
        coutryCodes.put("United States".toUpperCase(), "US");
        coutryCodes.put("Swaziland".toUpperCase(), "SZ");
        coutryCodes.put("Sudan".toUpperCase(), "SD");
        coutryCodes.put("South Sudan".toUpperCase(), "SS");
        coutryCodes.put("Suriname".toUpperCase(), "SR");
        coutryCodes.put("Syria".toUpperCase(), "SY");
        coutryCodes.put("Switzerland".toUpperCase(), "CH");
        coutryCodes.put("Sweden".toUpperCase(), "SE");
        coutryCodes.put("Tajikistan".toUpperCase(), "TJ");
        coutryCodes.put("Thailand".toUpperCase(), "TH");
        coutryCodes.put("Taiwan".toUpperCase(), "TW");
        coutryCodes.put("Tanzania".toUpperCase(), "TZ");
        coutryCodes.put("Togo".toUpperCase(), "TG");
        coutryCodes.put("Tokelau".toUpperCase(), "TK");
        coutryCodes.put("Tonga".toUpperCase(), "TO");
        coutryCodes.put("Trinidad And Tobago".toUpperCase(), "TT");
        coutryCodes.put("Tunisia".toUpperCase(), "TN");
        coutryCodes.put("Turkey".toUpperCase(), "TR");
        coutryCodes.put("Turkmenistan".toUpperCase(), "TM");
        coutryCodes.put("Tuvalu".toUpperCase(), "TV");
        coutryCodes.put("Uganda".toUpperCase(), "UG");
        coutryCodes.put("Ukraine".toUpperCase(), "UA");
        coutryCodes.put("Uruguay".toUpperCase(), "UY");
        coutryCodes.put("Uzbekistan".toUpperCase(), "UZ");
        coutryCodes.put("Vanuatu".toUpperCase(), "VU");
        coutryCodes.put("Wallis And Futuna".toUpperCase(), "WF");
        coutryCodes.put("Vatican".toUpperCase(), "VA");
        coutryCodes.put("Venezuela".toUpperCase(), "VE");
        coutryCodes.put("Hungary".toUpperCase(), "HU");
        coutryCodes.put("United Kingdom".toUpperCase(), "GB");
        coutryCodes.put("Vietnam".toUpperCase(), "VN");
        coutryCodes.put("Italy".toUpperCase(), "IT");
        coutryCodes.put("East Timor".toUpperCase(), "TL");
        coutryCodes.put("Ivory Coast".toUpperCase(), "CI");
        coutryCodes.put("Christmas Island".toUpperCase(), "CX");
        coutryCodes.put("Island Of Sint Maarten ( Dutch Part Of The Island )".toUpperCase(), "SX");
        coutryCodes.put("Cook Islands".toUpperCase(), "CK");
        coutryCodes.put("U.S. Virgin Islands".toUpperCase(), "VI");
        coutryCodes.put("Virgin Islands W.B".toUpperCase(), "VG");
        coutryCodes.put("Cocos".toUpperCase(), "CC");
        coutryCodes.put("Faroe Islands".toUpperCase(), "FO");
        coutryCodes.put("Św.Tomasza And Principe Islands".toUpperCase(), "ST");
        coutryCodes.put("Sao Tome And Principe , Islands".toUpperCase(), "SH");
        coutryCodes.put("Turks And Caicos Islands".toUpperCase(), "TC");
        coutryCodes.put("Zambia".toUpperCase(), "ZM");
        coutryCodes.put("Cape Verde".toUpperCase(), "CV");
        coutryCodes.put("Zimbabwe".toUpperCase(), "ZW");
        coutryCodes.put("United Arab Emirates".toUpperCase(), "AE");
    }

    public String code(String countryName) {
        return coutryCodes.get(countryName.toUpperCase());
    }
}
